language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

install:
  - pip install coveralls

script:
  # Securely load config.ini from external web service
  - curl -u $CONFDEPLOY_USER:$CONFDEPLOY_PASSWORD $CONFDEPLOY_URL > tests/config.ini

  # Run tests
  - cd tests
  - coverage run -m unittest discover -s ..

after_success:
  coveralls
